#!/usr/bin/env python3
"""Pass 3 mechanical shortlist over the rule register.

Reads docs/rule-register/rule-register-20260904T210000Z.md, normalizes each
row's rule+condition text, and emits every same-verb pair whose token-set
Jaccard >= 0.35 or whose difflib SequenceMatcher ratio >= 0.55 to
docs/rule-register/rule-candidates-20260904T223000Z.md.

Python 3 standard library only. No network. Deterministic.
"""

import difflib
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REGISTER = os.path.join(HERE, "rule-register-20260904T210000Z.md")
CANDIDATES = os.path.join(HERE, "rule-candidates-20260904T223000Z.md")

REGISTER_REV = "45b02c7b88a0e08f4872713aa39f840a59117423"

J_THRESHOLD = 0.35
R_THRESHOLD = 0.55

# Stated stopword list. Function words and register-generic verbs that carry no
# distinguishing content in a one-line rule statement.
STOPWORDS = frozenset("""
a an the this that these those there here
is are was were be been being am
do does did done doing
have has had having
of in on at to for from by with without within into onto upon over under
and or but nor so yet if then else than as
it its it's they them their theirs he she his her him hers
we us our ours you your yours i my mine
not no never any all each every some such other others another
which who whom whose what when where while whether why how
must shall should may might can could will would
one two both same only just also more most less least very
per via across about after before during until unless once
any-of no-op
""".split())

WORD_RE = re.compile(r"[^a-z0-9]+")


def normalize(rule, condition):
    """Lowercase, strip punctuation, collapse whitespace, drop stopwords."""
    raw = (rule or "") + " " + (condition or "")
    raw = raw.lower()
    raw = WORD_RE.sub(" ", raw)
    tokens = [t for t in raw.split() if t and t not in STOPWORDS]
    return tokens


def parse_register(path):
    rows = []
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip("\n")
            if not line.startswith("| R"):
                continue
            parts = line.split(" | ")
            parts[0] = parts[0].lstrip("| ")
            parts[-1] = parts[-1].rstrip(" |")
            if len(parts) < 8:
                sys.exit("malformed row: %r" % line[:120])
            rid, fname, lineno, binds, verb, rule, condition = parts[:7]
            rows.append(
                {
                    "id": rid.strip(),
                    "file": fname.strip(),
                    "line": lineno.strip(),
                    "binds": binds.strip(),
                    "verb": verb.strip(),
                    "rule": rule.strip(),
                    "condition": condition.strip(),
                }
            )
    return rows


def cell(text):
    return text.replace("|", "\\|").replace("\n", " ")


def main():
    rows = parse_register(REGISTER)
    for r in rows:
        toks = normalize(r["rule"], r["condition"])
        r["tokens"] = frozenset(toks)
        r["norm"] = " ".join(toks)

    by_verb = {}
    for r in rows:
        by_verb.setdefault(r["verb"], []).append(r)

    pairs = []
    for verb in sorted(by_verb):
        group = by_verb[verb]
        sm = difflib.SequenceMatcher(autojunk=False)
        for i in range(len(group)):
            a = group[i]
            sm.set_seq2(a["norm"])
            ta = a["tokens"]
            for j in range(i + 1, len(group)):
                b = group[j]
                tb = b["tokens"]
                union = len(ta | tb)
                jac = (len(ta & tb) / union) if union else 0.0
                if jac >= J_THRESHOLD:
                    sm.set_seq1(b["norm"])
                    ratio = sm.ratio()
                else:
                    sm.set_seq1(b["norm"])
                    if sm.real_quick_ratio() < R_THRESHOLD:
                        continue
                    if sm.quick_ratio() < R_THRESHOLD:
                        continue
                    ratio = sm.ratio()
                    if ratio < R_THRESHOLD:
                        continue
                pairs.append((a, b, jac, ratio))

    pairs.sort(key=lambda p: (-max(p[2], p[3]), p[0]["id"], p[1]["id"]))

    with open(CANDIDATES, "w", encoding="utf-8") as out:
        out.write("# Rule candidates — Pass 3 mechanical shortlist\n\n")
        out.write(
            "Derived artifact. Input: docs/rule-register/rule-register-%s @ %s. "
            "Generated by docs/rule-register/shortlist.py; Python 3 standard "
            "library only, no network, deterministic. Analysis only; no edits "
            "proposed to governed files.\n\n"
            % ("20260904T210000Z.md", REGISTER_REV)
        )
        out.write(
            "Thresholds: token-set Jaccard >= %.2f OR difflib SequenceMatcher "
            "ratio >= %.2f, over the normalized text (rule + condition, "
            "lowercased, punctuation stripped, whitespace collapsed, stopwords "
            "removed). Stopword list length: %d. Pairs are same-verb only "
            "(define pairs only with define). Rows read: %d. Pairs emitted: "
            "%d.\n\n"
            % (J_THRESHOLD, R_THRESHOLD, len(STOPWORDS), len(rows), len(pairs))
        )
        out.write(
            "Sorted by max(jaccard, ratio) descending, ties by id A then id B. "
            "The verdict column is filled at Step 2 with exactly one of `same`, "
            "`same-with-divergence`, `different`. The note column is empty here "
            "and carries `swept` on pairs the Step 2 sweep appends.\n\n"
        )
        out.write(
            "| pair | id A | id B | file A | file B | jaccard | ratio | rule A "
            "| rule B | verdict | note |\n"
        )
        out.write("|---|---|---|---|---|---|---|---|---|---|---|\n")
        for n, (a, b, jac, ratio) in enumerate(pairs, 1):
            out.write(
                "| %d | %s | %s | %s | %s | %.3f | %.3f | %s | %s |  |  |\n"
                % (
                    n,
                    a["id"],
                    b["id"],
                    cell(a["file"]),
                    cell(b["file"]),
                    jac,
                    ratio,
                    cell(a["rule"]),
                    cell(b["rule"]),
                )
            )

    counts = {v: len(g) for v, g in by_verb.items()}
    print("rows: %d" % len(rows))
    print("verb buckets: %s" % sorted(counts.items(), key=lambda kv: -kv[1]))
    print("stopwords: %d" % len(STOPWORDS))
    print("pairs: %d" % len(pairs))


if __name__ == "__main__":
    main()
